### ISSUE TITLE
??????????????????????

### ISSUE THREAD

**Issue by SEAPUNK** [choerodon/choerodon#1]
???

![screen shot 2018-01-11 at 12 34 15 pm](https://user-images.githubusercontent.com/4400726/34846053-c381e8ee-f6cb-11e7-899e-fe8b0cd0b8ec.png)

???????????????????????????????

![screen shot 2018-01-11 at 12 34 44 pm](https://user-images.githubusercontent.com/4400726/34846078-d351912a-f6cb-11e7-8c84-97125787c824.png)

??????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by CharlotteDunois** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by acarl005** [comment]
Perhaps this is an attempt to show how easy it is to buy GitHub stars from fake accounts (that are not super obviously fake at cursory glance)?

**Comment by paulonotz0r** [comment]
As you can see, this is a """"new"""" Chinese Click Farm.

**Comment by choerodon** [comment]
This is a platform used by our customers. My company has already announced open source and internally related preparations, including registration of GitHub account. The platform-related code and documents are under preparation and will be submitted as soon as possible。
