### ISSUE TITLE
支持Google cloud 部署吗

### ISSUE THREAD

**Issue by long0419** [choerodon/choerodon#10]
支持Google cloud 部署吗 ？！ 同题！

**Comment by vinkdong** [comment]
@long0419  你指的是Compute Engine 还是 Kubernetes Engine

**Comment by long0419** [comment]
Kubernetes Engine  ， K8s 在Google Cloud 上是最能体现效率的 。 如果能支持一键安装 。 会好很多  ，昨天尝试了下 ， 很多问题 。

**Comment by long0419** [comment]
现有主流平台我大致选择了fabric8 和 你们平台 ， fabric8 中文支持不好  ， 但是你们这个感觉还不成熟 。

**Comment by vinkdong** [comment]
@long0419 有任何问题和建议都可以在我们的论坛上提 http://forum.choerodon.io/ ，我们会及时解决和反馈的 🤝

**Comment by ganshanshan** [comment]
@long0419 非常感谢你的反馈，我们这边这几天测试了一下，现在还不能支撑AWS的 Kubernetes Engine，如你所说有很多的问题，我们已经记录下来，并在后续的版本中更新支持。
