### ISSUE TITLE
代码生成器是哪个项目啊

### ISSUE THREAD

**Issue by shirayner** [choerodon/choerodon#12]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the Choerodon logs and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of Choerodon
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by wmzzh117** [comment]
你好，请问你说的代码生成器是指？

**Comment by shirayner** [comment]
> 你好，请问你说的代码生成器是指？
[HZero文档平台](http://hzerodoc.saas.hand-china.com/docs/develop-guide/code-generator.html)上有个代码生成器的说明，能生成基于领域模型的猪齿鱼的四层结构的代码。
想知道猪齿鱼微服务框架中，哪个服务能实现生成这四层结构（api/app/domain/infra）的代码？

**Comment by wmzzh117** [comment]
你好，这个不是猪齿鱼的哦

**Comment by wmzzh117** [comment]
> > > 你好，请问你说的代码生成器是指？
> > > [HZero文档平台](http://hzerodoc.saas.hand-china.com/docs/develop-guide/code-generator.html)上有个代码生成器的说明，能生成基于领域模型的猪齿鱼的四层结构的代码。
> > > 想知道猪齿鱼微服务框架中，哪个服务能实现生成这四层结构（api/app/domain/infra）的代码？
> 
> 你好，这个不是猪齿鱼的哦

**Comment by shirayner** [comment]
> > > > 你好，请问你说的代码生成器是指？
> > > > [HZero文档平台](http://hzerodoc.saas.hand-china.com/docs/develop-guide/code-generator.html)上有个代码生成器的说明，能生成基于领域模型的猪齿鱼的四层结构的代码。
> > > > 想知道猪齿鱼微服务框架中，哪个服务能实现生成这四层结构（api/app/domain/infra）的代码？
> > 
> > 
> > 你好，这个不是猪齿鱼的哦


哦，我知道，那请问猪齿鱼有类似的代码生成器的功能来方便快速开发吗？

**Comment by wmzzh117** [comment]
> > > > > 你好，请问你说的代码生成器是指？
> > > > > [HZero文档平台](http://hzerodoc.saas.hand-china.com/docs/develop-guide/code-generator.html)上有个代码生成器的说明，能生成基于领域模型的猪齿鱼的四层结构的代码。
> > > > > 想知道猪齿鱼微服务框架中，哪个服务能实现生成这四层结构（api/app/domain/infra）的代码？
> > > 
> > > 
> > > 你好，这个不是猪齿鱼的哦
> 
> 哦，我知道，那请问猪齿鱼有类似的代码生成器的功能来方便快速开发吗？

暂时没有，后续可能会增加类似的功能。你可以持续跟进http://choerodon.io 了解我们的最新动态

**Comment by shirayner** [comment]
> > > > > > 你好，请问你说的代码生成器是指？
> > > > > > [HZero文档平台](http://hzerodoc.saas.hand-china.com/docs/develop-guide/code-generator.html)上有个代码生成器的说明，能生成基于领域模型的猪齿鱼的四层结构的代码。
> > > > > > 想知道猪齿鱼微服务框架中，哪个服务能实现生成这四层结构（api/app/domain/infra）的代码？
> > > > 
> > > > 
> > > > 你好，这个不是猪齿鱼的哦
> > 
> > 
> > 哦，我知道，那请问猪齿鱼有类似的代码生成器的功能来方便快速开发吗？
> 
> 暂时没有，后续可能会增加类似的功能。你可以持续跟进http://choerodon.io 了解我们的最新动态

强烈建议增加代码生成器的功能
