### ISSUE TITLE
对springcloud以外的微服务框架或者自定义的开发框架的支持

### ISSUE THREAD

**Issue by happyyangyuan** [choerodon/choerodon#13]
如题，请问一下是否支持使用自定义的开发框架而不使用springcloud？

**Comment by wmzzh117** [comment]
你好，使用choerodon开发并部署的应用本身而言是不限制框架类型的，即使是一个简单的java web应用或者其他语言构建的也是可以的。
如果想开发新的服务并集成到choerodon上，则建议使用spring cloud。

**Comment by ganshanshan** [comment]
@happyyangyuan 感谢关注猪齿鱼，如果在安装使用过程中有问题可以到社区的论坛上提交问题。社区的工程师会及时的回复解答。谢谢~~

社区论坛：http://forum.choerodon.io/

**Comment by happyyangyuan** [comment]
@wmzzh117 追问
1、如果我使用非springcloud微服务框架，猪齿鱼自带的调用链路追踪器、集中配置管理等配套设施是否就无法使用了呢？
2、请问一下是否支持在rancher2.0管理的k8s内部署猪齿鱼套件？

**Comment by wmzzh117** [comment]
@happyyangyuan 
1、调用链追踪和配置管理都是遵循spring cloud的规范。如果使用非spring cloud作为微服务框架，需要自行实现对应的功能才可以支持。
2、我们这边没有专门做rancher2.0 的k8s 支持测试，如果你在使用过程中有遇到问题可以和我们分享，一起讨论下解决方案

**Comment by happyyangyuan** [comment]
好的谢谢你们，我们后续继续深入调研
