### ISSUE TITLE
组织管理里面不能新建组织？

### ISSUE THREAD

**Issue by happyyangyuan** [choerodon/choerodon#17]
<img width="1279" alt="default" src="https://user-images.githubusercontent.com/9134975/48471406-ccfbe500-e82e-11e8-8cb0-7121af4f2303.png">

如图所示，“组织管理界面”没有如官方教程上描述的新建组织的按钮啊！

版本是0.10.0

**Comment by ganshanshan** [comment]
Hi ，感谢关注猪齿鱼，开源版本是没有对组织功能的。

**Comment by happyyangyuan** [comment]
哦，知道了。

**Comment by ganshanshan** [comment]
我们会把文档更新一下，感谢反馈！
