### ISSUE TITLE
what the hell?????????????????

### ISSUE THREAD

**Issue by zhangxiang958** [choerodon/choerodon#2]
a empty repo get 166 stars in one day ??????????????????????????????????????
what happened?????????????

**Comment by ruyazhang** [comment]
no reason!! there are so many people.

**Comment by choerodon** [comment]
This is a platform used by our customers. My company has already announced open source and internally related preparations, including registration of GitHub account. The platform-related code and documents are under preparation and will be submitted as soon as possible。
