### ISSUE TITLE
 What's the difference between openshift and choerodon?

### ISSUE THREAD

**Issue by maketubo** [choerodon/choerodon#5]
btw: the name of choerodon is an idea from docker?:)

**Comment by aronezhang** [comment]
OpenShift orgin is focused application lifecycle management and DevOps tooling.
Choerodon is focused microservice-based application analysis, design, development, management and DevOps tooling, In addition Choerodon also includes:
1. Agile project management
2. Portfolio project management(in development)
3. Scrum Board and KanBan Board management
4. SpringCloud-based microservice development framework
5. Service mesh for microservice safe and reliable(in development)
6. Knowledge management Wiki-based(in development) 
7. Other scenario-based business components

btw: Choerdon's logo will be introduced  in idea article.

**Comment by xxbandy** [comment]
开源是只开源了文档么，源代码在哪里啊。http://choerodon.io/zh/docs/installation-configuration/kubernetes/ 这个里面没有实质的东西啊

**Comment by superlee9527** [comment]
这个项目是我们的概要，你可以到https://github.com/choerodon，往下滑就可以看到源代码了

**Comment by superlee9527** [comment]
@xxbandy 这个项目是我们的概要，你可以到https://github.com/choerodon。
往下滑就可以看到源代码了
