### ISSUE TITLE
源码中缺少choerodon-socket-helper

### ISSUE THREAD

**Issue by LITAONO1** [choerodon/choerodon#7]
devops-service依赖choerodon-socket-helper，缺少choerodon-socket-helper.jar。

**Comment by crockitwood** [comment]
你好,因为我们工作的缺失,耽误了您的宝贵时间,我们现在已经上传到了oss中央仓库,https://oss.sonatype.org/content/groups/public/io/choerodon/choerodon-socket-helper/.
目前已可以通过oss中央库拉取.但还需要2个小时的时间同步到maven2.
      该库的代码近期也会上传到我们github仓库.
